spring.application.name=demo1


server.port=7080


spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto = update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:./demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

