spring.application.name=demo1


server.port=7080


spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.datasource.url=jdbc:h2:./demo
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

driver=oracle.jdbc.OracleDriver
url=jdbc:oracle:thin:@10.76.231.120:1521/Aynuat1?oracle.jdbc.timezoneAsRegion=false&SESSIONTIMEZONE=Asia/Baghdad&useUnicode=yes&characterEncoding=UTF-8&oracle.jdbc.defaultNChar=true
dbuser=MOBAPP
dbpassword=mobapp

springdoc.swagger-ui.path=/swagger-ui.html

ATTACHMENT_PATH=C:\\Users\\ASCF\\Desktop\\Omnia\\Attachments\\
